/**
 * The avatar object on the intro: one baked 640x640 coach intro in its glass panel,
 * a progress meter, the sound affordance, and the quote card that demonstrates the
 * gimmick before the user has done a rep.
 *
 * THE WATERMARK CROP — verify this with your eyes, not with reasoning. All three
 * baked clips carry a burned-in "This digital avatar is generated by AI" strip
 * across source y 93-99%, and all three put the eyeline at ~39% of frame height.
 * The stage is a square overflow-hidden cell; the video is blown up to
 * `--avatar-crop` (112%) and anchored to the TOP, which pushes the strip past the
 * bottom edge (93% x 112% = 104%) and leaves the eyeline at a portrait-correct
 * ~44%. Shrink that number and the watermark comes back onto the hero.
 *
 * THREE LAYERS, ONE PAINTED. A single <video> whose `src` changes paints nothing
 * while the next clip decodes, so a persona switch would flash black. Instead every
 * persona owns a mounted layer and the selected one is promoted to the front only
 * once it can actually paint — two clocks on purpose: the retint is instant, the
 * media swap waits for a real frame. Layers that are not in front are paused.
 *
 * SOUND IS EARNED, NEVER ASSUMED. The clips carry real audio, but a browser refuses
 * audible autoplay without a prior gesture, so a clip must START MUTED or it does
 * not start at all. `audible` flips only on a genuine gesture (a persona card, or
 * the affordance in the meter). Muted clips LOOP, because a silent face frozen on
 * its last frame reads as broken; an audible clip does NOT loop, because hearing the
 * same introduction on repeat is worse than silence. If an audible play is still
 * refused we fall back to muted and hand the affordance back — never a frozen frame.
 */
import { useCallback, useEffect, useRef, useState } from 'react'
import type { PersonaId } from '../types/tools'
import { PERSONA_ORDER, personaView } from './PersonaRail'

interface AvatarStageProps {
  readonly persona: PersonaId
  /** True once a real user gesture has earned sound. */
  readonly audible: boolean
  /** The user asked for sound (speaker affordance). */
  readonly onSoundRequest: () => void
  /** An audible play was refused — the parent must restore the affordance. */
  readonly onSoundRefused: () => void
}

const STAGE = {
  /** Never leave the panel stuck in "loading" because a decode was slow. */
  PROMOTE_TIMEOUT_MS: 1400,
  /** ~11 fps. Plenty for a 2px bar, and it keeps the swap off the render path. */
  METER_INTERVAL_MS: 90,
  /** HTMLMediaElement.HAVE_CURRENT_DATA — enough to paint one frame. */
  CAN_PAINT: 2,
} as const

const ZERO_CLOCK = '0:00'

function clock(seconds: number): string {
  const whole = Math.max(0, Math.floor(seconds))
  return `${Math.floor(whole / 60)}:${String(whole % 60).padStart(2, '0')}`
}

/**
 * Written straight to the DOM once every METER_INTERVAL_MS. React state at that
 * rate would re-render the whole intro — including three persona cards — for two
 * pixels of bar, which is the same reason App writes `--voice` by hand.
 */
function writeMeter(
  video: HTMLVideoElement | null,
  fill: HTMLDivElement | null,
  time: HTMLSpanElement | null,
): void {
  if (!fill || !time) return
  const duration = video && Number.isFinite(video.duration) ? video.duration : 0
  if (!video || duration <= 0) {
    fill.style.width = '0%'
    time.textContent = `${ZERO_CLOCK} / ${ZERO_CLOCK}`
    return
  }
  const at = Math.min(video.currentTime, duration)
  fill.style.width = `${((at / duration) * 100).toFixed(2)}%`
  time.textContent = `${clock(at)} / ${clock(duration)}`
}

export default function AvatarStage({ persona, audible, onSoundRequest, onSoundRefused }: AvatarStageProps) {
  const layers = useRef(new Map<PersonaId, HTMLVideoElement>())
  /**
   * Which layer is painted. Lags `persona` by one decode, never by more — and that
   * gap IS the loading state, so there is no second flag to keep in step with it.
   */
  const [shown, setShown] = useState<PersonaId>(persona)
  const [failed, setFailed] = useState(false)
  const fillRef = useRef<HTMLDivElement | null>(null)
  const timeRef = useRef<HTMLSpanElement | null>(null)

  const active = personaView(persona)

  const holdLayer = useCallback((id: PersonaId, element: HTMLVideoElement | null) => {
    if (element) layers.current.set(id, element)
    else layers.current.delete(id)
  }, [])

  // Promotion. The incoming layer is played MUTED first — that is the only kind of
  // play a browser grants unprompted, and it is what forces the first frame to
  // decode. Sound is applied afterwards, by the effect below, once it is in front.
  useEffect(() => {
    const next = layers.current.get(persona)
    if (!next) return undefined
    // Second belt: a layer that failed while it sat in the background has ALREADY
    // fired its error event, and it will not fire another one. Without this check a
    // dead clip would sit through the failsafe below and then promote a blank cell.
    if (next.error) {
      console.error(`[spotter] avatar clip is already in error: ${personaView(persona).introClip}`)
      setFailed(true)
      return undefined
    }
    setFailed(false)
    if (next.readyState >= STAGE.CAN_PAINT) {
      setShown(persona)
      return undefined
    }

    let settled = false
    const promote = () => {
      if (settled) return
      settled = true
      setShown(persona)
    }
    const fail = () => {
      if (settled) return
      settled = true
      setFailed(true)
      console.error(`[spotter] avatar clip failed to load: ${personaView(persona).introClip}`)
    }

    next.addEventListener('canplay', promote, { once: true })
    next.addEventListener('error', fail, { once: true })
    next.muted = true
    void next.play().catch((error: unknown) => {
      // Not fatal: `preload="auto"` still decodes, so `canplay` will promote anyway.
      console.warn('[spotter] avatar warm-up play refused', error)
    })
    const timer = window.setTimeout(promote, STAGE.PROMOTE_TIMEOUT_MS)

    return () => {
      settled = true
      window.clearTimeout(timer)
      next.removeEventListener('canplay', promote)
      next.removeEventListener('error', fail)
    }
  }, [persona])

  // The sound contract, applied to whichever layer is in front.
  useEffect(() => {
    // A failed stage has NO painted layer, so nothing may be playing: otherwise the
    // outgoing coach keeps talking behind a poster that names a different one.
    const element = failed ? null : (layers.current.get(shown) ?? null)
    layers.current.forEach((video) => {
      if (video !== element && !video.paused) video.pause()
    })
    if (!element) return

    element.muted = !audible
    element.loop = !audible
    if (audible) element.currentTime = 0
    void element.play().catch((error: unknown) => {
      if (!audible) {
        // A refused MUTED autoplay is survivable — the panel holds a poster frame.
        console.warn('[spotter] intro autoplay refused', error)
        return
      }
      // The browser did not credit our gesture. Drop back to a looping muted clip
      // and hand the affordance back, rather than dying on a frozen frame.
      console.warn('[spotter] audible intro play refused, falling back to muted', error)
      element.muted = true
      element.loop = true
      onSoundRefused()
      void element.play().catch((fallbackError: unknown) => {
        console.error('[spotter] intro clip will not play at all', fallbackError)
        setFailed(true)
      })
    })
  }, [shown, audible, failed, onSoundRefused])

  useEffect(() => {
    let frame = 0
    let at = 0
    const paint = (now: number) => {
      frame = window.requestAnimationFrame(paint)
      if (now - at < STAGE.METER_INTERVAL_MS) return
      at = now
      // Failed: no layer is painted, so the meter must read zero rather than keep
      // reporting the clip the user can no longer see.
      const front = failed ? null : (layers.current.get(shown) ?? null)
      writeMeter(front, fillRef.current, timeRef.current)
    }
    frame = window.requestAnimationFrame(paint)
    return () => window.cancelAnimationFrame(frame)
  }, [shown, failed])

  return (
    // "Loading" is exactly the gap between the selected persona and the painted
    // one — and a failure closes that gap, so the halo does not stay on forever
    // telling the user a clip is still on its way.
    <figure className="panel" data-loading={persona !== shown && !failed ? 'true' : 'false'}>
      <div className="stage" data-failed={failed ? 'true' : 'false'}>
        {PERSONA_ORDER.map((id) => (
          <video
            key={id}
            ref={(element) => holdLayer(id, element)}
            className="stage__video"
            data-front={id === shown ? 'true' : 'false'}
            src={personaView(id).introClip}
            muted
            playsInline
            preload="auto"
            aria-hidden="true"
            // Third belt: the promotion effect's listener is gone once a layer is in
            // front, so a decode failure MID-PLAY would otherwise freeze unnoticed.
            onError={() => {
              console.error(`[spotter] avatar clip error: ${personaView(id).introClip}`)
              if (id === persona) setFailed(true)
            }}
          />
        ))}

        <div className="stage__fallback">
          <div>
            <span className="stage__fallbackName">{active.name}</span>
            <p className="stage__fallbackNote">Avatar clip unavailable</p>
          </div>
        </div>

        <div className="stage__scrim" aria-hidden="true" />
        <div className="stage__rim" aria-hidden="true" />

        <span className="badge">
          <span className="badge__dot" aria-hidden="true" />
          {active.name}
        </span>
      </div>

      <div className="meter">
        <div className="track">
          <div className="track__fill" ref={fillRef} />
        </div>
        <span className="time" ref={timeRef}>
          {`${ZERO_CLOCK} / ${ZERO_CLOCK}`}
        </span>
        <button
          type="button"
          className="sound"
          data-on={audible ? 'true' : 'false'}
          disabled={audible}
          aria-label={audible ? `Sound on. ${active.name} is talking.` : 'Hear your coach'}
          onClick={onSoundRequest}
        >
          <span className="sound__dot" aria-hidden="true" />
          {audible ? 'Sound on' : 'Muted · tap to hear'}
        </button>
      </div>

      <figcaption className="caption">
        <span className="caption__k">Same bad rep, three reactions</span>
        {/* Keyed on persona so the swap re-animates instead of silently retexting. */}
        <p className="caption__q" key={persona}>
          {active.reaction}
        </p>
      </figcaption>
    </figure>
  )
}
